name: somd2

channels:
  - conda-forge
  - openbiosim/label/dev

dependencies:
  - biosimspace
  - git
  - filelock
  - loguru
  - numba
  - pycuda
  - pip:
      - git+https://github.com/openbiosim/loch
